import { BookOpen, Bot, Database, FileText } from "lucide-react";
import type { ResponseMeta } from "@/lib/api";
import { rh } from "@/lib/remote-hub";
import { cn } from "@/lib/utils";

interface ResponseModeBadgeProps {
  meta: ResponseMeta;
  className?: string;
}

export function ResponseModeBadge({ meta, className }: ResponseModeBadgeProps) {
  const isVectorRag = meta.rag_mode === "vector";
  const isLlm = meta.llm_mode === "llm";

  return (
    <div className={cn("flex flex-wrap items-center gap-1.5", className)}>
      <span
        className={cn(
          rh.badge,
          "rounded-md px-2 py-0.5 normal-case tracking-wide"
        )}
        title={
          isVectorRag
            ? `Retrieved ${meta.rag_chunk_count} chunks from indexed knowledge base`
            : "Using built-in fallback knowledge snippets"
        }
      >
        {isVectorRag ? <Database className="size-3" /> : <BookOpen className="size-3" />}
        {isVectorRag ? "RAG" : "Mock RAG"}
      </span>
      <span
        className={cn(
          rh.badge,
          "rounded-md px-2 py-0.5 normal-case tracking-wide"
        )}
        title={isLlm ? "Generated by LLM (Groq/OpenAI)" : "Predefined scripted response"}
      >
        {isLlm ? <Bot className="size-3" /> : <FileText className="size-3" />}
        {isLlm ? "LLM" : "Scripted"}
      </span>
      {isVectorRag && meta.rag_sources.length > 0 && (
        <span
          className="max-w-[220px] truncate text-[10px] text-muted-foreground"
          title={meta.rag_sources.join(", ")}
        >
          {meta.rag_sources[0]}
          {meta.rag_sources.length > 1 ? ` +${meta.rag_sources.length - 1}` : ""}
        </span>
      )}
    </div>
  );
}
